# Generated by Django 5.1.6 on 2025-02-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('occupancy', models.IntegerField()),
                ('hour_of_day', models.IntegerField()),
                ('energy_consumption', models.FloatField()),
            ],
        ),
    ]
